# pyproject.toml

[tool.flake8]
exclude =  [
    "src/resources",
    "src/tests",
    ".git",
    "__pycache__",
]
ignore = ["E501", "W503"]
per-file-ignores = [
    '__init__.py:F401',
]
max-line-length = 100

[tool.pytest.ini_options]
bdd_features_base_dir = "tests/features"
testpaths = ["tests"]
python_files = ["test_*.py"]
pythonpath = ["."]
addopts = """
    --html=reports/report.html
    --self-contained-html
    --cov=.
    --cov-report=term
    --cov-report=html:reports/coverage
"""
